# Generated by Django 3.0.7 on 2020-07-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200715_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='activate',
            new_name='active',
        ),
    ]
